name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: 14
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_number }}
  PERCY_PARALLEL_TOTAL: 1

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v3

      - name: Check lockfile version
        uses: mansona/npm-lockfile-version@v1

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint


  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}

      - run: npm i -g npm@9

      - name: Install dependencies
        run: npm ci

      - run: npm run clone

      - name: Test
        env:
          PERCY_PARALLEL_NONCE: ${{ env.PERCY_PARALLEL_NONCE }}
          PERCY_PARALLEL_TOTAL: ${{ env.PERCY_PARALLEL_TOTAL }}
          PERCY_TOKEN: 5ad6687f6b1ad3dec2b964f94d3d59ff3880baccf1492c0663e85c1ce79c1a52
        run: npx percy exec -- npm run test:ember
